--merging all four tables
WITH unicorn_companies AS( 

	SELECT *

	FROM (
		SELECT COMPANY_ID
		FROM COMPANIES
		 ) AS ALL_COMPANY_ID_INFO
	
	INNER JOIN INDUSTRIES USING(COMPANY_ID)

	INNER JOIN  (
		SELECT COMPANY_ID, VALUATION 
		FROM FUNDING
		) AS VALUATION_INFO USING(COMPANY_ID)

	INNER JOIN (
		SELECT COMPANY_ID, EXTRACT(YEAR FROM DATE_JOINED) AS YEAR
		FROM DATES
		WHERE EXTRACT(YEAR FROM DATE_JOINED) IN (2019, 2020, 2021)
		) AS DATES_ADJUSTED USING(COMPANY_ID)
		
), 

--filter for top 3 industry names
filter AS( 
	SELECT INDUSTRY, COUNT(COMPANY_ID)
	FROM unicorn_companies
	GROUP BY INDUSTRY
	ORDER BY COUNT DESC
	LIMIT 3
)

SELECT DISTINCT INDUSTRY, 
		YEAR,
		COUNT(COMPANY_ID) AS NUM_UNICORNS,
		ROUND(AVG(VALUATION) / 1000000000, 2) AS AVERAGE_VALUATION_IN_BILLIONS 
				
FROM unicorn_companies

WHERE INDUSTRY IN(
	SELECT INDUSTRY
	FROM filter
	)

GROUP BY INDUSTRY, YEAR
ORDER BY YEAR DESC, NUM_UNICORNS DESC